name: my_pytorch_env  # Name of the environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  # Specify Python version (adjust if necessary)
  - pytorch=1.13.0  # Specify the PyTorch version (adjust if needed)
  - cudatoolkit=11.3  # Use the appropriate CUDA version for your system
  - pip  # Ensure pip is included
  - pip:
